### ISSUE TITLE
Create Kafka Migration Sample

### ISSUE THREAD

**Issue by Asitha** [wso2/integration-studio-examples#106]
**Description:**

Create a sample that is similar to https://docs.mulesoft.com/connectors/kafka/kafka-connector-examples 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dilee** [comment]
Fixed in https://github.com/wso2/integration-studio-examples/pull/109
